### ISSUE TITLE
Refactor YAML files

### ISSUE THREAD

**Issue by lorixhack** [Team-Isaac-Polito/reseq_ros2#47]
We want to separate the YAML configuration files in smaller YAML files where each of them will contain a separate part of the codebase:

- Robot parameters (number of modules, physics parameters, type of CAN bus ecc ...) for the two versions of the robot
- Digital twin parameters (xacro)
- Sensors (realsense and other sensors in future)
- Reseq controllers

You can find the config files in this directory: `reseq_ros2`/`reseq_ros2`/`config`

The idea is to create a script which will generate the YAML file for the specific configuration we will want to launch, including the other base YAML files. 

See #37 for more info

**Comment by Yusuf-Serdar** [comment]
It sounds like a good idea. But I'm not sure I'm getting the point of the script right. Correct me if I'm wrong.

My objective would be that
- each reseq robot (mk1 and mk2) keep its own `reseq_mk?.yaml` containing only its specific configuration
- but each specific configuration file would reference the externalized YAML containing the common configuration, e.g. creating a `digital_twin_params.yaml` file for configuring _xacro_ dictionary key values, and other separate YAML files for _enea_consts_, _scaler_consts_, etc.

If there is no problem so far, my question about the script is that
- do we select the specific configuration we will want to launch dynamically at launch time
- or modify the script to select specific configurations

Any further clarification on the script would be great.

**Comment by luca-byte** [comment]
As you may have seen we have different YAML configuration files in the `config` directory and the differences between some of them are small (for example between the `*_can.yaml` and `*_vcan.yaml` versions the only difference is the can interface). Moreover certain config files break modularity (like at the moment `reseq_controllers.yaml` is explicitly expecting two modules, uses data from other existing YAML files that was copied there and is called [directly](https://github.com/Team-Isaac-Polito/reseq_ros2/blob/f5eb81cbd46deb4fc438420376c55f4213be9fb5/reseq_ros2/launch/reseq_launch.py#L121) breaking modularity)

The objective of your task is to look at the current YAML status and create from some atomic YAML files the ones we will actually use in the launch file, merging the atomic YAML files together.

About the specific files to create, I leave it up to you to decide, but feel free to ask question if something is not clear. Consider that the CAN version should be for the physical robot, the VCAN shares most of the geometric configs (since it is a digital *twin*) but the sensors should be different (even if they are yet to be implemented for the DT). Moreover the `*_controllers_*.yaml` should be only programmatically created since  they use data taken from other YAML files. The EnEA constants make sense only for the MK1 robot since the MK2 will have a significantly different end effector

From what I understand you have correctly identified the objective and reason behind the task, I just added some details. I really suggest you to make the design choices, given these explanations of our intentions.
