### ISSUE TITLE
Make agevar compatible with robot and Gazebo

### ISSUE THREAD

**Issue by GBergatto** [Team-Isaac-Polito/reseq_ros2#7]
Agevar needs to publish to both `diff_cont_X` and `reseq/moduleX/motors/setpoint`

**Comment by marc0777** [comment]
Yes, but to be honest I don't know what to rewrite in particular and how, since the configuration file is hard-coded inside the robot description:

https://github.com/Team-Isaac-Polito/reseq_ros2/blob/4a9232a473ddb054e590d0b1f5a4474bd40532ee/reseq_gazebo/description/reseq_parameters.xacro#L6-L10

This is extremely not portable and doesn't for example even work on my setup, for the usual problem that I my ROS workspace is different than the configuration suggested in the readme. 

However I'm afraid that to improve this we would need to therefore change one (or more) of the xacro files, and maybe it's not the right moment for that. What do you think?

**Comment by Tizio0o0o0o** [comment]
Can I help? I'm not quite sure about the problem, can you explain it?

**Comment by marc0777** [comment]
The difference in structure is also one of the reason for whch I'd postpone this problem for now, even though we'll have to address it sooner than later (we are already accumulating more backlog than we should, considering we're only one month into this repository).
